tab = int(input('Digite o numero para gerar a tabuada: '))

print('01 X {} = {}'.format(tab, tab * 1))
print('02 x {} = {}'.format(tab, tab * 2))
print('03 x {} = {}'.format(tab, tab * 3))
print('04 x {} = {}'.format(tab, tab * 4))
print('05 x {} = {}'.format(tab, tab * 5))
print('06 x {} = {}'.format(tab, tab * 6))
print('07 x {} = {}'.format(tab, tab * 7))
print('08 x {} = {}'.format(tab, tab * 8))
print('09 x {} = {}'.format(tab, tab * 9))
print('10 x {} = {}'.format(tab, tab * 10))